# Создаём Бандл приложения
- name: "Install {{app_name}} with bundler module"
  community.general.bundler:
    state: present
    deployment_mode: yes
    chdir: "{{ app_dir }}"
    executable: /usr/local/bin/bundle
    extra_args: --clean --no-cache
    exclude_groups: development
