#Ставим права на папки
- name: "Change right to folder app"
  ansible.builtin.command: "bash -lc 'cd {{ app_dir }} && cd .. && sudo chown -R vagrant x'"
# Не успеваю сделать красиво - исправлю

# Устанавливаем модуль Бандла
- name: "Install bundle module"
  ansible.builtin.command: "bash -lc 'cd {{ app_dir }} && sudo gem install bundler -v 1.16.2'"

- name: "Change right to folder /usr/local/rvm/gems/ruby-2.6.1/wrappers directory"
  ansible.builtin.command: "bash -lc 'cd '/usr/local/rvm/gems/ruby-2.6.1/wrappers directory' && cd .. && sudo chown -R vagrant 'wrappers directory''"
# Не успеваю сделать красиво - исправлю


# Конфигурируем Бандл
- name: "Config {{app_name}} with bundler module"
  ansible.builtin.command: "bash -lc 'cd {{ app_dir }} && sudo bundle config build.nokogiri --use-system-libraries'"

# Устанавливаем Бандл
- name: "Install {{app_name}} with bundler module"
  community.general.bundler:
    state: present
    deployment_mode: yes
    chdir: "{{ app_dir }}"
    executable: /usr/local/bin/bundle
    extra_args: --clean --no-cache
    exclude_groups: development

#command -a 'bash -lc "gem install bundler"' -u your_rbenv_user

#- name: "Install bundler & dependencies"
#  ansible.builtin.command: "{{ item }}"
#  args:
#    chdir: "{{ app_dir }}"
#  loop:
#    - "gem install bundler -v 1.16.2"
#    - "bundle config build.nokogiri --use-system-libraries"
#    - "bundle install --clean  --no-cache --without development"
#  ignore_errors: yes
