# Создаём Бандл приложения
- name: "Config {{app_name}} with bundler module"
  ansible.builtin.command: bash -lc 'cd {{ app_path }} && bundle config build.nokogiri --use-system-libraries'

- name: "Install {{app_name}} with bundler module"
  community.general.bundler:
    state: present
    deployment_mode: yes
    chdir: "{{ app_dir }}"
    executable: /usr/local/bin/bundle
    extra_args: --clean --no-cache
    exclude_groups: development
