#Копируем содержимое папки assets в папку public
- name: "Copy folder assets to public"
  ansible.builtin.copy:
    src: "{{ app_dir }}/app/assets"
    dest: "{{ app_dir }}/public"
#    owner: vagrant
#    group: vagrant
#    mode: '0644'
    remote_src: yes
#    directory_mode: yes
#  when: not app_files.stat.exists
