#Проверяем есть папка с приложением, результат пишем в переменную
- name: "Check exists directory"
  stat:
    path: "{{ app_dir }}"
  register: app_files

#Создаём папки
- name: "Create app folder"
  ansible.builtin.file:
      path: /applications
      owner: root
      group: root
      mode: '0644'
      state: directory
  when: not app_files.stat.exists

- name: "Create app folder 2"
  ansible.builtin.file:
      path: /applications/xapps
      owner: root
      group: root
      mode: '0644'
      state: directory
  when: not app_files.stat.exists

#Копируем проект с GIT репозитория, если папки нет
- name: "Copy {{ app_name }} files from the repo project"
  ansible.builtin.git:
    repo: "https://{{ gitlab_user | urlencode }}:{{ gitlab_password | urlencode }}@gitlab.slurm.io/edu/xpaste_practicum.git"
    dest: "{{ app_dir }}"
  when: not app_files.stat.exists

#Копируем содержимое папки assets в папку public
- name: "Copy folder assets to public"
  ansible.builtin.copy:
    src: "{{ app_dir }}/app/assets"
    dest: "{{ app_dir }}/public"
  when: not app_files.stat.exists
