#Проверяем есть папка с приложением, результат пишем в переменную
- name: "Check exists directory"
  stat:
    path: "{{ app_dir }}"
  register: app_files

#Создаём папки
- name: "Create app folder"
  ansible.builtin.file:
      path: /applications
#      owner: vagrant
#      group: vagrant
#      mode: '0644'
      state: directory
  when: not app_files.stat.exists

- name: "Create app folder 2"
  ansible.builtin.file:
      path: /applications/xapps
#      owner: vagrant
#      group: vagrant
#      mode: '0644'
      state: directory
  when: not app_files.stat.exists

#Копируем проект с GIT репозитория, если папки нет
- name: "Copy {{ app_name }} files from the repo project"
  ansible.builtin.git:
    repo: "https://{{ gitlab_user | urlencode }}:{{ gitlab_password | urlencode }}@gitlab.slurm.io/edu/xpaste_practicum.git"
    dest: "{{ app_dir }}"
  when: not app_files.stat.exists
