# Вставляем список зависимостей для приложения в плейбук
- name: "Include variables"
  include_vars: dependencies.yml

#Устанавливаем репозиторий
- name: "Adding repo for ruby package"
  ansible.builtin.yum:
    name: centos-release-scl-rh
    state: present
    update_cache: yes

# Устанавливаем зависимости приложения
- name: "Install dependencies {{ app_name }}"
  ansible.builtin.yum:
    name: "{{ app_dependencies }}"
    state: latest
    update_cache: yes

#Чиним стили
- name: "Config /config/puma-production.rb"
  ansible.builtin.replace:
    path: "{{ app_dir }}/config/environments/production.rb"
    regexp: "config.public_file_server.enabled = ENV['RAILS_SERVE_STATIC_FILES'].present?"
    replace: "config.public_file_server.enabled = true"
