---
# tasks file for deploy_app

# Устанаваливаем зависимости приложения
- include_tasks: install_dependencies.yml

# Копируем с репозитория приложение
- include_tasks: copy_files_git.yml

# Разворачиваем приложение правильным способом (soft)
- include_tasks: install_app_soft.yml
  when: soft choose_your_love

# Разворачиваем приложение альтернативным способом (hard)
- include_tasks: install_app_hard.yml
  when: hard choose_your_love
