# Выполняем миграцию базы данных.

# Решил вынести миграцию базы данных в отдельный таск, а не делать миграцию
# перед каждым запуском, как по заданию. Мне кажется это более правильно
# запускать миграции отдельно при смене версии приложения, чем делать миграцию
# при каждом запуске приложения - это же займет время + лишний риск потери данных.

# Выполнил коммандом, т.к. не смог найти как это сделать индемпотентно.
# Если найду способ как сделать миграцию БД красиво - исправлю.

- name: "Migrate base"
  command:
/bin/bash -lc 'source /etc/profile.d/rvm.sh; SECRET_KEY_BASE={{ SECRET_KEY_BASE }} RAILS_ENV={{ RAILS_ENV }} RAILS_LOG_TO_STDOUT={{ RAILS_LOG_TO_STDOUT }} DB_HOST={{ DB_HOST }} DB_PORT={{ DB_PORT }} DB_NAME={{ DB_NAME }} DB_USER={{ DB_USER }} DB_PASSWORD={{ DB_PASSWORD }} bundle exec rake db:migrate'
