---
# vars file for install_postgres
postgresql_data_dir: "/var/lib/pgsql/data"
postgresql_bin_path: "/usr/bin"
postgresql_daemon: "postgresql"
postgresql_user_to_nix: "postgres"
postgresql_packages:
    - postgresql
    - postgresql-server
    - python-psycopg2
    - python-ipaddress
