---
- name: "Install {{ app_name }} and configure"
  hosts: "xapps_node"
  become: true
  vars:
#  Эти переменные надо определить ОБЯЗАТЕЛЬНО

#   Здесь задаем имя приложения
    app_name: xapps

#   Здесь задаем версию ruby
    ruby_version: "ruby-2.6.1"

#  Здесь задаются данные для доступа к репозиторию проекта
    gitlab_user: ""
    gitlab_password: ""

#   Это очень важная переменная, без неё плейбук не отработает.
#   Здесь мы выбираем способ разворачивания нашего приложения =)
#   Надо выбрать soft или hard
#   true - Правильный способ установки. Этот вариант должен быть по умолчанию, но еще не дописаны rb файлы.
#   false - Для любителей "пожестче" ;)
#   способ true не дописан!!! В работе
    choose_your_love: false

#   Эти переменные можно не определять. Если их не определить -
#   тогда возьмутся дефолтные значения из ~./ansible/install_postgres/defaults/main.yml
#    db_name: "xappsdb"
#    db_user: "xapp"
#    db_password: ""

#    Эти переменные возьмутся из ~./ansible/deploy_app/defaults/main.yml
#    app_socket: "/tmp/puma.sock"
#    app_node:"xapps_node"
#    RAILS_ENV: production
#    RAILS_LOG_TO_STDOUT: 1


  pre_tasks:
  - name: Update ca-certificates
    yum: name=ca-certificates state=latest


  roles:
  - geerlingguy.repo-epel
  - geerlingguy.repo-remi
  - geerlingguy.nginx
  - { role: rvm.ruby,
      tags: ruby,
      rvm1_rubies: "['{{ ruby_version }}']",
      rvm1_install_flags: '--auto-dotfiles',
      rvm1_install_path: /usr/local/rvm,
      rvm1_user: root,
      rvm1_gpg_key_server: 'hkp://keyserver.ubuntu.com'
    }
  - install_postgres
  - deploy_app
