---
- name: "Install {{ app_name }} and configure"
  hosts: "xapps_node"
  become: true
  vars:
#   Здесь задаем имя приложения
    app_name: xapps
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: 1

#  Эти переменные надо определить ОБЯЗАТЕЛЬНО
#  Здесь задаются данные для доступа к репозиторию проекта
    gitlab_user: ""
    gitlab_password: ""

#   Это очень важная переменная, без неё плейбук не отработает.
#   Здесь мы выбираем способ разворачивания нашего приложения =)
#   Надо выбрать soft или hard
#   soft - Правильный способ установки. Этот вариант по умолчанию.
#   hard - Для любителей "пожестче" ;)
    choose_your_love: "soft"
#   Здесь задаем версию ruby
    ruby_version: "ruby-2.6.0"

#   Эти переменные можно не определять. Если их не определить -
#   тогда возьмутся дефолтные значения из ~./ansible/install_postgres/defaults/main.yml
#    db_name: ""
#    db_user: ""
#    db_password: ""
#    app_socket: ""
#    app_node:""


#  pre_tasks:
#  - name: Update ca-certificates
#    yum: name=ca-certificates state=latest


  roles:
#  - geerlingguy.repo-epel
#  - geerlingguy.repo-remi
#  - geerlingguy.nginx
#  - { role: rvm.ruby,
      tags: ruby,
      rvm1_rubies: "['{{ ruby_version }}']",
      rvm1_install_flags: '--auto-dotfiles',
      rvm1_install_path: /usr/local/rvm,
      rvm1_user: root,
      rvm1_gpg_key_server: 'hkp://keyserver.ubuntu.com'
    }
#  - install_postgres
#  - deploy_app
