app_dependencies:
      - git
      - nodejs
      - "@development-tools"
      - libxml2-devel
      - libxslt-devel
      - postgresql-devel
      - libpqxx-devel
      - ruby-devel
#      - ffi:1.9.23
#      - puma:3.11.3
#      - nokogiri
