---
# handlers file for deploy_app
  - name: "Reload nginx"
    service:
      name: nginx
      state: reloaded

  - name: "Reload {{ app_name }}"
    service:
      name: "{{ app_name }}"
      state: reloaded

  - name: "Reload systemctl"
    ansible.builtin.command: systemctl daemon-reload
    become: true
